outputs:
    B1:
        device: 'tektronix'
        channel: 2
        active: true # available: false, true
        func: 'SIN' # available funcs: 'SIN'
        methods: ['freq'] # available methods: 'freq', 'amp', 'offset', 'const', 'freq_mod.span', 'freq_mod.sweep_time', 'freq_mod.return_time', 'amp_mod.freq', 'amp_mod.depth'
        freq:
            start: 2.0e3
            stop: 6.e3
            step: 0.5e3
            label: 'B1 frequency (Hz)'  # TODO
        amp:
            start: .14
            stop: 2.5
            step: 0.5
            label: 'B1 amplitude (V)'
        offset:
            start: 0.
            stop: 0.
            step: 0.
            label: 'B1 offset (V)'
        # frequency modulation settings (cannot be combined with amplitude 
        # modulation)
        freq_mod:
            active: false
            center: 1.1E3
            span:
                start: 1.5E3
                stop: 0.
                step: 0.
                label: 'B1 frequency modulation span (Hz)'
            sweep_time:
                start: 2.
                stop: 0.
                step: 0.
                label: 'B1 frequency modulation sweep time (s)'
            return_time:
                start: 2.
                stop: 0.
                step: 0.
                label: 'B1 frequency modulation return time (s)'
            hold_time: 0
            form: 'LIN'
        # amplitude modulation settings (cannot be combined with frequency 
        # modulation)
        amp_mod:
            active: false
            waveform: 'SIN'  # available waveforms: 'SIN', 'SQU', 'TRI'
            depth:
                start: 50
                stop: 50
                step: 10
                label: 'B1 amplitude modulation depth (%)'
            freq:
                start: 50
                stop: 350
                step: 10
                label: 'B1 amplitude modulation frequency (Hz)'
    B0:
        device: 'tektronix'
        channel: 1
        active: true
        func: 'RAMP' # available funcs: 'DC', 'RAMP', 'SQU'
        methods: ['const'] # available methods: 'freq', 'amp', 'offset', 'const'
        freq:
            start: 1.
            stop: 0.
            step: 0.
            label: 'B0 frequency (Hz)'
        amp:
            start: 1.0
            stop: 3.0
            step: 0.1
            label: 'B0 amplitude (V)'
        offset:
            start: 0.0
            stop: 0.15
            step: 0.01
            label: 'B0 offset (V)'
    R3:
        device: 'hameg'
        channel: 2
        active: false
        func: 'DC'
        methods: ['const'] # available methods: 'offset', 'const'
        offset:
            start: 0.009
            stop: 0.8
            step: 0.05
            label: 'R3 offset (V)'
    R2:
        device: 'hameg'
        channel: 1
        active: false
        func: 'DC'
        methods: ['const'] # available methods: 'offset', 'const'
        offset:
            start: 0.082
            stop: 0.8
            step: 0.05
            label: 'R2 offset (V)'
    R4:
        device: 'hameg'
        channel: 3
        active: false
        func: 'DC'
        methods: ['const'] # available methods: 'offset', 'const'
        offset:
            start: 0.083
            stop: 0.9
            step: 0.05
            label: 'R4 offset (V)'
stack:
    - 'B1.0'
devices:
    nidaq:
        sample_rate: 2000000.0
        measurement_time_s: 1.
        downsampling_factor: 100
measurement:
    cell_id: 4
    measurement_id: 6
    rubidium_isotope: 85
    laser_locked: 'true'
    temperature_C: 44.7
    laser_power_uW: 13
    photo_diode_gain_dB: 60
    shields: 4
    NV_in_cell: false
    NV_light_on: false
    NV_light_power_mW: 59
    NV_chopper_on: false
    NV_chopper_freq: 70
    NV_microwave_on: false
    NV_microwave_level_dBm: 0
    NV_microwave_am_freq: 50e3
    extra_resistances:
        R0: 1800
        R1: 'high pass'
        R2: 1800
        R3: 1800
        R4: 1800
    polarity: 
        R2: '+=+, -=-'
        R3: '-=+, +=-'
        R4: '-=+, +=-'
    lock_in_params:
        active: false  # false: measure photodiode signal, true: measure lock-in output signal
        time_constant_ms: 3
        sensitivity_mV: 0.3
        slope_dB: 24
        sync_filter: True
        ground: 'float'
        filters:
            - 'line'
            - '2xline'
        reserve: 'low_noise'
        phase: '15deg'
        harmonic: 1
