outputs:
    B1:
        device: 'tektronix'
        channel: 2
        active: true
        func: 'SIN'
        method: 'freq' # bzw. 'amp', 'offset', 'const' #, 'freq_mod.sweep_time'
        freq:
            start: 2e3
            stop: 6e3
            step: 1e3
        amp:
            start: 0.5
            stop: 0.0
            step: 0.0
        offset:
            start: 0.
            stop: 0.
            step: 0.
        # frequency modulation settings (cannot be combined with amplitude 
        # modulation)
        freq_mod:
            active: false
            center: 1E3
            #center:
            #    start: 1E3
            #    stop: 1E4
            #    step: 1E2
            span: 500
            sweep_time: 0.5
            return_time: 0.5
            hold_time: 0
            form: 'LIN'
        # amplitude modulation settings (cannot be combined with frequency 
        # modulation)
        amp_mod:
            active: false
            waveform: 'SIN'
            depth: 50
            freq: 30
    B0:
        device: 'tektronix'
        channel: 1
        active: true
        func: 'RAMP' # bzw. 'RAMP', 'SQU', 'DC'
        method: 'amp' # bzw. 'freq', 'amp', 'const'
        freq:
            start: 1
            stop: 0.
            step: 0.
        amp:
            start: 0.2
            stop: 1.0
            step: 0.1
        offset:
            start: 0.
            stop: 0.
            step: 0.
    R3:
        device: 'hameg'
        channel: 1
        active: false
        func: 'DC'
        method: 'offset' # bzw. 'const'
        offset:
            start: 0.
            stop: 0.
            step: 0.

    R2:
        device: 'hameg'
        channel: 2
        active: false
        func: 'DC'
        method: 'offset' # bzw. 'const'
        offset:
            start: 0.
            stop: 0.
            step: 0.
    R4:
        device: 'hameg'
        channel: 3
        active: false
        func: 'DC'
        method: 'offset' # bzw. 'const'
        offset:
            start: 0.
            stop: 0.
            step: 0.
            
stack:
    - B0
    - B1
devices:
    nidaq:
        measurement_time_s: 1.0
        downsampling_factor: 100
measurement:
    cell_id: 4
    measurement_id: 50
    rubidium_isotope: 85
    temperature_C: 46.5
    laser_power_uW: 10
    photo_diode_gain_dB: 40
    lock_in_params:
        active: false
        time_constant_ms: 10
        sensitivity_mV: 5
        slope_dB: 24
        sync_filter: True
        ground: 'float'
        filters:
            - 'line'
            - '2xline'
        reserve: 'low_noise'
